### ISSUE TITLE
Swift/Java sdks for iOS/Android

### ISSUE THREAD

**Issue by Rajan** [hoxton-one/deepstream.io#52] opened 2015-12-29 11:32 UTC
Kudos for building first truly real-time framework using RethinkDB. A great initiative!
It'd be great to be able to easily build mobile apps using Firebase/Parse like SDKs.
What would be best approach to get started on this?

**Comment by WolframHempel** [comment] 2015-12-29 13:34
Hi @Rajan,
thanks for raising this, your timing is perfect. We've been working on a number of resources to make it easier to develop deepstream clients in different languages ([epic here](https://github.com/hoxton-one/deepstream.io-website/issues/25)).

The main cornerstone will be a detailed protocol spec with all the messages the client sends/receives and the expected behaviors, written in Gherkin (the cucumber test language that's language agnostic).

You can already find these [protocol specs here](https://github.com/hoxton-one/deepstream.io-client-specs/tree/master/features), once they're completed we'll also add them to the info-section of deepstream.io.

For a general overview over how deepstream's messages are structured, please have a look [here](http://deepstream.io/tutorials/message-structure.html)

When it comes to getting started, here's how I would tackle it:
1) Establish a TCP connection to your deepstream server
2) Send authentication message and await response ([spec here up to line 17](https://github.com/hoxton-one/deepstream.io-client-specs/blob/master/features/logging-in.feature))
3) Start with events as they are the simplest concept
4) ... everything else

An Android/iOS client is a great initiative, if we can help in any way, please don;t hesitate to write to us (info@hoxton-one.com) or get in touch via Slack

**Comment by Rajan** [comment] 2016-01-06 04:31
Thank you for a detailed response. I was traveling last week. Now, I'll take a look.

**Comment by WolframHempel** [comment] 2016-01-12 15:40
Message Specs are online: http://deepstream.io/info/messagestructure/connectivity.html

**Comment by yasserf** [comment] 2016-01-22 14:29
This seems to be a duplicate of #68 and #67 

Closing this issue so we can distinguish between work on android and iOS client libraries

**Closed by yasserf** 2016-01-22 14:29 UTC
