### ISSUE TITLE
RPC functions routed through another deepstream server do not run second time around

### ISSUE THREAD

**Issue by petemill** [hoxton-one/deepstream.io#59] opened 2016-01-06 21:13 UTC
I have a sample setup consisting of:
 - 1 redis server
 - 1 deepstream server listening on TCP 6021 (conductor1.js)
 - 1 deepstream server listening on TCP 6023 (conductor2.js)
 - 1 client, connecting to TCP 6021, and providing RPC functions `testfn1` and `testfn3` (functionhost1.js)
 - 1 client, connecting to TCP 6023, and providing RPC functions `testfn2` and `testfn3`  (functionhost2.js)
 - 1 client, connecting to TCP 6021, and calling RPC functions `testfn1`, `testfn2`, and `testfn3` (client1.js)

Simulatenously, I run `node conductor1.js` `node conductor2.js` `node functionhost1.js` and `node functionhost2.js` and all the connections are successfully established.

When I run `client1.js` the first time, it successfully finds the functions on both function hosting deepstream clients. When I run it any subsequent times, it only successfully runs the functions from the deepstream host it is connected to, and gets an ACK timeout for the function running on the other deepstream function-hosting server.

Output from first run:
```
› node client1.js
Processed testfn1. Response  Any Name processed
Processed testfn3. Response  Any Name processed
Processed testfn1. Response  Any Name processed
Processed testfn3. Response  Any Name processed
Processed testfn2. Response  Any Name processed
Processed testfn2. Response  Any Name processed
```

Output from second and subsequent runs:
```
› node client1.js
Processed testfn1. Response  Any Name processed
Processed testfn3. Response  Any Name processed
Processed testfn1. Response  Any Name processed
Processed testfn3. Response  Any Name processed
ACK_TIMEOUT
Processed testfn2. Response  undefined
ACK_TIMEOUT
Processed testfn2. Response  undefined
```

I have provided a test repository with all the code neccessary to reproduce this issue. This can be accessed at https://github.com/petemill/debug-issuereproduce-deepstream-distributedcalls.

I am running node v4.2.1

Thanks

**Comment by petemill** [comment] 2016-01-07 04:05
If this gets merged and published, I believe this will be solved. Strange noone else noticed this. Is the RPC functionality not commonly used?

**Comment by WolframHempel** [comment] 2016-01-07 07:01
Hi @petemill ,

thanks for raising this and providing the amazing description. This sounds indeed very worrying and I am wondering why our tests wouldn't have triggered it (We're not only testing the Redis message connector as a standalone library, but are also using it in the automated cluster e2e tests for the Node client (https://github.com/hoxton-one/deepstream.io-client-js/tree/master/test-e2e). At a first glance your solution makes perfect sense. Let us run a few more tests and I'll update this issue very shortly.

**Comment by WolframHempel** [comment] 2016-01-07 07:41
Could replicate the described behaviour using https://github.com/petemill/debug-issuereproduce-deepstream-distributedcalls.git

### First run
![run-1](https://cloud.githubusercontent.com/assets/1503717/12164998/42411524-b51a-11e5-9cc9-248f70d1afc4.png)

### Second run
![run-2](https://cloud.githubusercontent.com/assets/1503717/12165004/4cace150-b51a-11e5-8daa-553925e5b82c.png)

**Comment by WolframHempel** [comment] 2016-01-07 08:07
I think the reason we haven't encountered this problem earlier is, that it is specific to the redis msg connector. Other connectors, e.g. the [AMQP one already implement the behaviour](https://github.com/hoxton-one/deepstream.io-msg-amqp/blob/master/src/message-connector.js) that @petemill added in [his pull request](https://github.com/hoxton-one/deepstream.io-msg-redis/pull/3)

**Comment by WolframHempel** [comment] 2016-01-07 08:40
I've tested and merged https://github.com/hoxton-one/deepstream.io-msg-redis/pull/3 and we've released deepstream.io-msg-redis 0.2.7 containing the fix.

I've also raised https://github.com/hoxton-one/deepstream.io-client-js/issues/53 to add an E2E test covering this specific scenario.

Again, thanks so much for raising this, I hope you enjoy using deepstream apart from this issue.

**Closed by WolframHempel** 2016-01-07 08:40 UTC
Labels: bug
